image: alpine

pages:
  script:
  - apk --no-cache add py3-pip python-dev
  - pip3 install sphinx sphinx_rtd_theme
  - apk --no-cache add make
  - cd docs/
  - sphinx-build source build
  - cd -
  - mv docs/build/html public/
  artifacts:
    paths:
    - public
  only:
  - master
